version: '3'

services:
  
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: posgres_db
            port: '5432'
            database: prisma_data            
            user: prisma
            password: secreta
            migrations: true
    networks:       
      service:         

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: secreta
      POSTGRES_DB: prisma_data
    networks:       
      service:         
        aliases:           
          - posgres_db

#####################################################################
# Networks

networks:
  service: