#==========================  Modules configuration =============================
filebeat.modules:

#=========================== Filebeat prospectors ==============================
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - '/data/*.log'
  json.message_key: log
  json.add_error_key: true
  json.keys_under_root: true
  processors:
    - add_locale: ~
  multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
  multiline.match: after

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5045"]
